### ISSUE TITLE
`GLIBC_2.28' not foun on Ubuntu 16.04

### ISSUE THREAD

**Issue by kunzhipeng** [multiprocessio/dsq#103]
OS: Ubuntu 16.04.5 64bit
dsq Version: dsq-linux-x64-v0.22.0.zip

Error:
./dsq: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./dsq)

**Comment by eatonphil** [comment]
Since this is an older distro you may be able to grab the source code and build it yourself on Ubuntu 16.04.

I don't think I'll have prebuilt binaries that support these older versions.

If you run into trouble building from source feel free to ask for help then!
