### ISSUE TITLE
table "t_0" already exists on Windows 10

### ISSUE THREAD

**Issue by kunzhipeng** [multiprocessio/dsq#104]
OS: Windows 10
dsq Version: dsq-win32-x64-v0.23.0

Error:

C:\Users\Administrator\Downloads\dsq-win32-x64-v0.23.0>dsq.exe  eleme_shops_ningbo_20221125.csv -i
table "t_0" already exists

**Comment by philippgille** [comment]
I'm getting the same error on macOS, dsq installed with Go, `v0.23.0`.

When I ran the command for the first time it worked, then it exited after I entered a `?`, and each subsequent execution of the CLI leads to that error. This is from my terminal:

```
$ dsq /path/to/redacted.csv -i
Cache invalid, re-import required.
dsq> ?
near "?": syntax error
$ dsq /path/to/redacted.csv -i
table "t_0" already exists
```

**Comment by philippgille** [comment]
Just saw #101, this appears to be a duplicate and can probably be closed as such

**Comment by eatonphil** [comment]
Yep let's close this for 101.
