### ISSUE TITLE
Search multiple files

### ISSUE THREAD

**Issue by AFgh24** [multiprocessio/dsq#106]
Hello
I need to search in some parquet files
But it only searches the first file
It does not search the second or third file

dsq **user1.parquet**  **userdata2.parquet**  "SELECT * FROM {} WHERE **user** REGEXP '**test**'" > result.csv

Please help me

**Comment by eatonphil** [comment]
You need to follow the [multiple file syntax](https://github.com/multiprocessio/dsq#multiple-files-and-joins) and use a UNION to go across them.

So `(SELECT * FROM {1} UNION SELECT * FROM {2}) WHERE user REGEXP 'test'`.
