### ISSUE TITLE
SQLite driver without CGO (modernc.org/sqlite)

### ISSUE THREAD

**Issue by franchb** [multiprocessio/dsq#12]
There is a SQLite driver that doesn't use CGO: https://pkg.go.dev/modernc.org/sqlite

Using this it would be possible to avoid external dependencies.

**Comment by eatonphil** [comment]
That's an interesting idea but would require a lot of testing especially since there is nothing in that repo about what level of compatibility they have.

**Comment by eatonphil** [comment]
I did some basic performance testing and on large datasets this library is more than 2x as slow as the original C code. Not exactly surprising and I don't have a compelling reason to avoid cgo so I don't think I'll be adopting this library any time soon.

**Comment by eatonphil** [comment]
Published my benchmarks finally here: https://datastation.multiprocess.io/blog/2022-05-12-sqlite-in-go-with-and-without-cgo.html
