### ISSUE TITLE
MacOS Homebrew formulae

### ISSUE THREAD

**Issue by aheissenberger** [multiprocessio/dsq#20]
It would nice to have a [Homebrew](https://brew.sh) formulae to allow easier version updates.

Maybe this tool can help:
https://jkawamoto.github.io/fgo/

**Comment by eatonphil** [comment]
Hey! Yes this would be great. I don't have time to focus on this at the moment but I would accept a PR that automates this, whether that's you or another user.

**Comment by tingwei628** [comment]
It has already had [dsq](https://formulae.brew.sh/formula/dsq) on Homebrew

**Comment by tingwei628** [comment]
[dsq](https://formulae.brew.sh/formula/dsq) on Homebrew

**Comment by eatonphil** [comment]
Oh wow! Out of curiosity, if you know, how do they keep it up to date when there are new releases?

**Comment by tingwei628** [comment]
@eatonphil I think [this article](https://extrawurst.medium.com/github-actions-homebrew-%EF%B8%8F-2789ae5023fd) would be helpful ?

**Comment by eatonphil** [comment]
Thanks! Looks like it's a manual process. Well I'm going to close this because it's on brew already!

**Comment by eatonphil** [comment]
I also added a section in the readme about the homebrew option.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/3925912/156935990-c67dd127-c061-4eb2-b49e-dfc03290348a.png">
