### ISSUE TITLE
Can't query data from a nested json

### ISSUE THREAD

**Issue by guolaopi** [multiprocessio/dsq#21]
![图片](https://user-images.githubusercontent.com/11360515/155642267-f6f71368-f716-4cb7-80ec-fff6c54aa9c1.png)
It's tips "no such a column"

**Comment by eatonphil** [comment]
Oh you're right. You need to escape the quotes with backslashes if you are using PowerShell.

```
dsq .\testdata\nested\nested.json 'select name, \"location.city\" from {}'
[{"location.city":"Toronto","name":"Agarrah"},
{"location.city":"Mexico City","name":"Minoara"},
{"location.city":"New London","name":"Fontoon"}]
```

I'll update the docs to note this.

I don't know PowerShell that well so there may be another way. Open to suggestions.

**Comment by guolaopi** [comment]
![图片](https://user-images.githubusercontent.com/11360515/155672726-42321013-6b8b-4c7b-bc0a-dc48459d653b.png)
It's works. Cmd has same problem. Thanks.

**Comment by eatonphil** [comment]
Good point, thank you! I'll include powershell and cmd in the docs update.
