### ISSUE TITLE
Script release process and host binaries on Github release page

### ISSUE THREAD

**Issue by eatonphil** [multiprocessio/dsq#3]
So users don't need to install Golang to get this.

**Comment by jauderho** [comment]
Any reason to not use goreleaser? Might be easier rather than rolling your own.

See https://github.com/jauderho/bl3auto/blob/main/.goreleaser.yml for an example.

**Comment by eatonphil** [comment]
@jauderho that's a neat project! I like that it can do some package manager packaging for you like .deb and homebrew packages. Thanks for the recommend, I'll take a closer look.
