### ISSUE TITLE
Bug:  sql: converting argument $3 type: unsupported type []interface {}, a slice of interface

### ISSUE THREAD

**Issue by chr-b** [multiprocessio/dsq#36]
I am using the following input file `data.jsonl`:
```
{"valuea":"1","valueb":"2","valuec":["1.5.68"]}
```

Executing query `dsq data.jsonl "select valuea from {0}"` results in the following error: ` sql: converting argument $3 type: unsupported type []interface {}, a slice of interface`

Using dsq-linux-x64-0.8.1

**Comment by chr-b** [comment]
BTW, it's the array of `valuec` that is triggering the problem.

**Comment by eatonphil** [comment]
Fixed now in the 0.9.0 release. You can now fully access that data, it's not just ignored. See the readme for details:

![image](https://user-images.githubusercontent.com/3925912/159769081-09dbc4c7-c895-44b3-87ce-4ec2075cb819.png)
