### ISSUE TITLE
Support of an input SQL file

### ISSUE THREAD

**Issue by matrixise** [multiprocessio/dsq#48]
Like `jq` or some other CLIs, there is a flag for an external file `-f`.

For example, with `jq`, we can use `jq -f script.jq` 

That will be really useful in some cases, for example, when you want to define a lot of queries.

`dsq -f query.sql file1.json file2.json file3.json` 

Thank you

**Comment by eatonphil** [comment]
That's a good idea!

**Comment by Ghibranalj** [comment]
Working on it

**Comment by eatonphil** [comment]
Closed in #49. Thanks @Ghibranalj for the fast work!

Releasing this shortly.

**Comment by eatonphil** [comment]
This is now available in dsq 0.15.1!

**Comment by matrixise** [comment]
Hey, thank you for the feature.

Have a nice day,

**Comment by jberger** [comment]
Is this documented anywhere? Neither the cli help nor the github front page (as recommended by the help) mention this but luckily I found this issue! Perhaps consider documenting it?

**Comment by eatonphil** [comment]
Feel free to add it to the docs @jberger!
