### ISSUE TITLE
Terminate output with newline?

### ISSUE THREAD

**Issue by vegarsti** [multiprocessio/dsq#5]
What a cool and great tool! Not sure about you, but I always like command-line tools to add a final newline at the end. Maybe just because my terminal complains when it isn't the case: When I run this, I get a `%` sign at the end.

```bash
$ dsq imdb.csv 'select title from {}'
[{"Title":"Shawshank Redemption"}
,
{"Title":"The Godfather"}
,
{"Title":"The Godfather: Part II"}
,
{"Title":"The Dark Knight"}
,
{"Title":"12 Angry Men"}
]%
$
```

I looked around in the code but wasn't immediately sure where to suggest adding this, though.

**Comment by eatonphil** [comment]
Yeah this is annoying! At the moment I pipe the result of dsq through jq when I want pretty formatting. But I suppose I could add a flag for pretty (or in pretty) formatting to dsq itself.

**Comment by vegarsti** [comment]
You could e.g. add

```go
fmt.Fprintln(os.Stdout, "")
```

at the end of main.go, after this: https://github.com/multiprocessio/dsq/blob/dedd036b10c5e2b2991bc27ef94204eed8c0703f/main.go#L270

If you pipe the output from dsq into something else I don't think this would interfere with something

**Comment by eatonphil** [comment]
If you'd like, make a PR that does so! You may need to fix the one test in ./scripts/test.sh that tests literal result comparison and you'd just need to add a newline to the expected string.

**Comment by vegarsti** [comment]
For sure, will do!
