### ISSUE TITLE
Bug: duplicate column name in CSV input file

### ISSUE THREAD

**Issue by chr-b** [multiprocessio/dsq#74]
The input file:
```
"a","a b"
"line1","1"
```

Executing a query over this file:
```
$ dsq input.csv  "select * from {}"
duplicate column name: a
```

Not sure if there is any definition of whether CSV headers support whitespaces, but i just stumbled over an input file that does that.

**Comment by eatonphil** [comment]
This happened because fields weren't being quoted in SQLite. It's fixed now in 0.20.2. Thanks for the report!
