### ISSUE TITLE
Suggestion for Comparisons section

### ISSUE THREAD

**Issue by simonw** [multiprocessio/dsq#8]
This section here: https://github.com/multiprocessio/dsq/tree/dedd036b10c5e2b2991bc27ef94204eed8c0703f#comparisons

`sqlite-utils memory` is another tool (that I built) which can do this.

Documentation: https://sqlite-utils.datasette.io/en/stable/cli.html#querying-data-directly-using-an-in-memory-database

Blog entry with more examples: https://simonwillison.net/2021/Jun/19/sqlite-utils-memory/ - plus a video demo at https://www.youtube.com/watch?v=OUjd0rkc678

Supported file types are JSON, newline-JSON, CSV and TSV. I haven't done any benchmarks on it - it's using SQLite under the hood but the tool itself is written in Python.

**Comment by eatonphil** [comment]
Hey thanks! It might be a good starting place for you to make a PR against octosql with support for their benchmark since that is what I'd like to set up dsq for as well: https://github.com/cube2222/octosql/blob/main/benchmarks/benchmarks.sh.

**Comment by eatonphil** [comment]
I added a link to sqlite-utils to the comparison section.
