### ISSUE TITLE
Parquet is missing rows

### ISSUE THREAD

**Issue by mariussoutier** [multiprocessio/dsq#81]
I have a Parquet file that should have 30,000+ rows, but `SELECT COUNT(*) FROM {}` returns `7000`. Another one with more than 40,000 rows returns exactly `8000`. Converting the same data to JSON works fine.

**Comment by eatonphil** [comment]
Thanks for the report! Can you share a parquet file that has this issue?

**Comment by mariussoutier** [comment]
Unfortunately no, it's business-related. But nothing special, 30 or so columns with mostly UTF8 and two INT32 types.

**Comment by eatonphil** [comment]
Sounds like @sajuno reproduced the issue and is thinking of a fix. Thanks @sajuno!

**Comment by eatonphil** [comment]
Closed in #82 now available in dsq 0.21.0
