### ISSUE TITLE
suggestion to use v prefix for tags

### ISSUE THREAD

**Issue by kamilsk** [multiprocessio/dsq#83]
Hi! Based on this approach https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module to track tool dependencies for a module, as [an example](https://github.com/kamilsk/dotfiles/blob/b7c282d8b5ca726aae7c751a4bc0bcf5e90a9058/toolset/tools.go#L18), I found a slight inconvenience when working with `dsq`, because `dsq` uses a different style to name tags. For `go mod`, it's recommended by this https://go.dev/ref/mod#versions

> Each version starts with the letter v, followed by a semantic version

As a result, I have a pseudo-version [like this](https://github.com/kamilsk/dotfiles/blob/b7c282d8b5ca726aae7c751a4bc0bcf5e90a9058/toolset/go.mod#L16) instead of `v0.21.0`. It's challenging to understand which version is under the hood, actually. Is it possible to change the naming convention for tags?

**Comment by eatonphil** [comment]
Interesting but why are you importing dsq at all? It isn't intended to be a library.

**Comment by kamilsk** [comment]
I use it as tool, but use `go mod` to manage it's version instead of https://github.com/multiprocessio/dsq#build-and-install-from-source.

**Comment by kamilsk** [comment]
Long story short. For example, I have a project where `dsq` will be helpful. I pack its tools together like this https://github.com/octomation/go-service/blob/main/tools/tools.go.

And use some magic
- https://github.com/octomation/go-service/blob/c1e6a708f6ac420de14981d812b03c46ed430aa0/Makefile#L333-L338
- https://github.com/octomation/go-service/blob/main/bin/activate
